# # version: '3'

# # services:
# #   frontend:
# #     build:
# #       context: ./frontend
# #       dockerfile: Dockerfile
# #     ports:
# #       - "3000:3000"
# #     restart: always
# #     depends_on:
# #       - backend
# #     environment:
# #       - REACT_APP_API_URL=http://localhost:4000/api

# #   backend:
# #     build:
# #       context: ./backend
# #       dockerfile: Dockerfile
# #     ports:
# #       - "4000:4000"
# #     restart: always
# #     environment:
# #       - NODE_ENV=production
# #       - PORT=4000
# #       - DATABASE_URL=mongodb://mongo:27017/myapp

# #   admin:
# #     build: ./Admin
# #     ports:
# #       - "5173:5173"
# #     depends_on:
# #       - backend
# #     environment:
# #       - VITE_API_URL=http://localhost:4000/api
# #     volumes:
# #       - ./Admin:/app
# #       - /app/node_modules

# #   mongo:
# #     image: mongo:latest
# #     ports:
# #       - "27017:27017"
# #     volumes:
# #       - mongo-data:/data/db
# #     restart: always

# # volumes:
# #   mongo-data:


# # version: '3.8'

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "4000:4000"
#     depends_on:
#       - mongo
#     environment:
#       - MONGO_URI=mongodb+srv://Yashodha:23072@cluster0.hlwt8dd.mongodb.net/e-commerce?retryWrites=true&w=majority&appName=Cluster0
#     volumes:
#       - ./backend:/app
#     restart: unless-stopped

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     restart: unless-stopped

#   admin:
#     build: ./Admin
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend
#     environment:
#       - VITE_API_URL=http://localhost:4000/api
#     volumes:
#       - ./Admin:/app
#       - /app/node_modules

#   mongo:
#     image: mongo:latest
#     container_name: mongo_container
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     restart: unless-stopped

# volumes:
#   mongo-data:


version: '3.8'
services:
  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://Yashodha:23072@cluster0.hlwt8dd.mongodb.net/e-commerce?retryWrites=true&w=majority&appName=Cluster0
      - PORT=4000
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map container port 80 to host port 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000/api  # Use service name for internal communication
    restart: unless-stopped
    networks:
      - app-network

  admin:
    build: 
      context: ./Admin
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:4000/api  # Use service name for internal communication
    volumes:
      - ./Admin:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
